### ISSUE TITLE
Files without categories read ok

### ISSUE THREAD

**Issue by locsmith** [uwbmrb/PyNMRSTAR#100]
If i don't add a category in the API of a frame the API complains loudly, but importing a star file without categories in the Saveframe doesn't raise warnings. Is this correct?

**Comment by jonwedell** [comment]
This is in accordance with the https://en.wikipedia.org/wiki/Robustness_principle.

Basically, a user of PyNMR-STAR may be reading files from a variety of sources, some of which have been generated by others, and may have issues. Unless the issue is so severe that it prevents coherent parsing entirely, the library attempts to accept what it is given when reading files.

On the other hand, if you are creating NMR-STAR files yourself, the library does its best to push you to generate correct files to the best of its ability.

**Comment by jonwedell** [comment]
As with your other issue though, a more dedicated NEF-mode may enable me to silence some of these warnings where not appropriate. I'll definitely consider it further.
