### ISSUE TITLE
pynmrstar should use its own logger?!

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#108]
It would be helpful if pynmrstar used its own logger so when silencing warnings such as 

``` WARNING:root:Loop with no data on line: xx```

warnings could be silenced for pynmrstar and not the libraries

**Comment by dmaziuk** [comment]
I'm pretty sure loop with no data is an invalid construct in STAR so if anything, that particular one should throw an exception -- or at least be logged as critical error

**Comment by jonwedell** [comment]
> I'm pretty sure loop with no data is an invalid construct in STAR so if anything, that particular one should throw an exception -- or at least be logged as critical error

It logs it as a warning, which I think is more appropriate than a critical error or even an error. A critical error [implies that the program may not be able to continue](https://www.logicmonitor.com/blog/python-logging-levels-explained#logging-levels) - but an empty log in no way impedes the operation of the program. Allowing empty loops when parsing seems to me to best conform to the https://en.wikipedia.org/wiki/Robustness_principle.

It used to be possible to specify a module-level `raise_parse_warnings` value to cause issues like this to cause the raising of an exception rather than just logging about them. In the major 3.0 refactor when these module-level variables went away it looks like that functionality became hidden to the end user - only available if using the Parser() class directly. I've pushed commits which in the next release will restore this functionality to the end user so that when calling Entry.from_file() (for example) the user can specify `raise_parse_warnings=True` to access this behavior.

**Comment by jonwedell** [comment]
> t would be helpful if pynmrstar used its own logger

Work on that was in progress but never completed - thanks for the reminder. I've just taken a look again and will have an update rolled out shortly to resolve this issue.

**Comment by jonwedell** [comment]
Resolved in newly released version 3.3.1.

Release notes: https://pynmrstar.readthedocs.io/en/latest/release-notes.html#id1
