### ISSUE TITLE
should PyNMRSTAR describe itself as a star file parser

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#112]
pynmrstar/parser.py:73

raise ParsingError("Invalid file. NMR-STAR files must start with 'data_' followed by the data name. "
                               f"Did you accidentally select the wrong file? Your file started with '{self.token}'.",
                               self.line_number)

would be better to be 

raise ParsingError("Invalid file. STAR files must start with 'data_' followed by the data name. "
                               f"Did you accidentally select the wrong file? Your file started with '{self.token}'.",
                               self.line_number)

since PyNMRSTAR can be used as a general statement file parser?

**Comment by jonwedell** [comment]
PyNMR-STAR can be used to parse NMR-STAR-like files (NEF comes to mind) but it isn't a true STAR parser, for two reasons. 

First, there are some NMR-STAR conventions which are not part of the STAR specification that it enforces. For example, the `_Category.tag` convention for tags is part of NMR-STAR v3 and not part of the STAR specification. STAR only requires that a "data name" begin with a `_` but not that it contain a `.`. PyNMR-STAR enforces this convention.

Second, there are aspects of the STAR specification that PyNMR-STAR does not implement. Relevant to the particular example you gave, STAR files may also start with a `global_` global block identifier rather than `data_` and that isn't supported in PyNMR-STAR.

If you're using the library to parse NEF or other NMR-STAR like files and end users may see these exception messages, you could probably do something like:

```code
try:
    pynmrstar_action()
except pynmrstar.ParsingError as e:
    error_text = str(e).replace("NMR-STAR", "NEF")
    raise pynmrstar.ParsingError(error_text) from e # Could also raise from None if you want to suppress the context of the original error
```

**Comment by dmaziuk** [comment]
STAR file can start with a comment, `data_`, or `global_`, and contain multiple global and/or data blocks. NMR-STAR (and mmCIF) can start with `data_` or comment and contain a single data block that ends on EOF. I forget if a file containing only comment(s) is a valid-but-empty STAR file, or a (non-empty?) block of either kind is actually required.

**Comment by varioustoxins** [comment]
thanks for the reply John that makes sense for where pynmrstar is coming from

**Comment by varioustoxins** [comment]
As an aside I am trying to validate a nef file against the nef validation dic which is an mmcid dic (mmcif_nef_v1_1.dic *) which includes _datablock.id constructs I guess I am out of luck with pynmstar in this case ...


* https://github.com/NMRExchangeFormat/NEF/blob/master/specification/mmcif_nef_v1_1.dic

**Comment by dmaziuk** [comment]
NMR-STAR allows only saveframes at data block level. Dictionary files have tags and/or loops there and won't be read by an NMR-STAR parser. There's a .dic file parser in `SAS`, it should read the NEF dictionary. 

`Starobj` creates a relational database from the dictionary and loads a file in there, i.e. that validates the file structure: right tags in the right saveframes etc. I haven't looked at NEF closely so I don't know if that would work for it "as is".

**Comment by varioustoxins** [comment]
@dmaziuk thank you,  sas sounds like the simplest answer other than making my own fork of pynmrstar, could you point me to the dic parser I had a look but wasn't clear where its was?

**Comment by dmaziuk** [comment]
it's under `ddl` in https://github.com/bmrb-io/SAS/tree/master/python/sas. I think `python3` branch should work though I haven't done much testing on it. This file: https://github.com/bmrb-io/onedep2bmrb/blob/master/pdbx2bmrb/pdbx_dict.py is the usage example (reads PDBx v.40 .dic, not tested w/ python 3) and this: https://github.com/bmrb-io/SAS/blob/master/python/scripts/quickcheck.py (2.7 only) may be of use too.
