### ISSUE TITLE
running the tests fails with missing file naughty-strings/blns.json

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#113]
```ERROR: test_odd_strings (pynmrstar.unit_tests.TestPyNMRSTAR)
Make sure the library can handle odd strings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/xxxx/PyNMRSTAR/pynmrstar/unit_tests/__init__.py", line 57, in test_odd_strings
    with open(os.path.join(our_path, 'naughty-strings/blns.json')) as odd_string_file:
FileNotFoundError: [Errno 2] No such file or directory: '/xxx/PyNMRSTAR/pynmrstar/unit_tests/naughty-strings/blns.json'
```

**Comment by jonwedell** [comment]
I'd recommend installing pynmrstar from PyPI or install it using setup.py if at all possible rather than running it out of a local directory - otherwise you'll need to either manually compile the C extension for faster tokenization and formatting, or it will run far slower.

If you want to run the unit tests locally, you'll need to check out the naughty-strings submodule. To do that, go to the root of your pynmrstar checkout and run

```bash
git submodule init
git submodule update
```

and then the units tests will work.
