### ISSUE TITLE
Is uniform indenting possible

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#116]
Currently the indenting in star files produced by pynmrstar uses 3 spaces per level, but many editors are setup to use 2 or more typically 4 spaces per ident level. Is it possible to control the indentation level in an output star file...

**Comment by varioustoxins** [comment]
Having looked at the code I could create a fork and contribute via a push...

**Comment by jonwedell** [comment]
This isn't possible without breaking the parser behavior in a specific edge case. If you add data to a tag which contains `\n;\n` (which would normally be used as the tag delimiter) the library indents in by three spaces to avoid it from producing invalid NMR-STAR output. The alternative would be refusing to allow such data values at all. This is not technically part of the NMR-STAR standard, but it ensures the library always produces output that it itself can always parse back in again. If you used variable indentation, it wouldn't be possible to determine if a data value with this specific property were present and escaped using spaces or not. Admittedly this is quite the edge case, and if you don't expect to encounter such data values in your code you're welcome to modify your fork to use different indentation, but I wouldn't want to update the reference implementation in such a way that prevents it from having the property of always being able to reliably parse it's own output.

See, for example:

```
>>> import pynmrstar
>>> a = pynmrstar.Saveframe.from_scratch('test', 'test')
>>> a.add_tag('test', '\nsome\nvalue')
>>> print(a)
save_test
   _test.test
;

some
value
;

save_

>>> a['test'] = """
... save_test
...    _test.test
... ;
... 
... some
... value
... ;
... 
... save_
... """
>>> print(a)
save_test
   _test.test
;

   save_test
      _test.test
   ;
   
   some
   value
   ;
   
   save_
   
;

save_

```

Most text editors I've used allow configuring the number of spaces that an indent is, so updating your editor to use 3 for ".str"/".nef" files could be another option if you don't want the added burden of maintaining a configurable indentation level in your own fork.

If you do go to update this in yours, you'll probably want to strip out this edge-case handling behavior or update it. (It's also present in the c code: https://github.com/bmrb-io/PyNMRSTAR/blob/v3/c/cnmrstarmodule.c#L558-L579)

**Comment by dmaziuk** [comment]
I'm not sure I follow: as I recall the delimiter is `\n;`, it can't be a value. A `[^\n]+;` can only be a part of semicolon (or STAR-2012 triple-quote) -delimited value (because of the newline), which you normally handle with lexer states. *If* you support the triple-quotes. which I don't think anyone does, this (and triple-single-quote) should be valid:
```
_sometag """multi-line value
;
with new-line-semilcolon inside"""
```
but AFAICT that  is the only way a `\n;` is legal in a value. SAS should parse that correctly though I don't think I have a test case for it there.

Edit: and I don't remember what STAR-2012 rules are for triple-semicolons: maybe it has to be `\n['"]{3}` ...

**Comment by jonwedell** [comment]
PyNMR-STAR doesn't support STAR-2012 triple-quoted values. (Like you said, nothing else does anyways.)

> but AFAICT that is the only way a \n; is legal in a value. SAS should parse that correctly though I don't think I have a test case for it there.

This is the issue - since it's plausible you would find an `\n;` in the text block of some output put in the description tag of a saveframe, disallowing that didn't make sense to me. Indenting it to get `   ;\n` so that it can be wrapped in the standard `\n;` delimiter seemed a better option to me. It's clear to any human reading what the original data value was, whereas not allowing data with that specific character sequence would probably wind up with:

1) Users being surprised that that specific character sequence can't be represented.
2) Users doing some hacky escaping of their own for the data, such that there is no standard way to encode `\n;` inside an NMR-STAR tag.

That's why I opted to implement handling of this case in PyNMR-STAR the way I did.

**Comment by dmaziuk** [comment]
Well, that's the point: you wouldn't find a `\n;` in text block because it's the closing digraph for the text block. A `[^\n]+;` in a text block is trivially handled by using lexical states in which case the exact number of `[^\n]`'s in there doesn't matter.
