### ISSUE TITLE
Data loss occurred while output if proper key tag was missing

### ISSUE THREAD

**Issue by yokochi47** [uwbmrb/PyNMRSTAR#87]
[test_nmr-star_3.1.txt](https://github.com/uwbmrb/PyNMRSTAR/files/4900287/test_nmr-star_3.1.txt)

Hi Jon,

I noticed that data loss occurred while outputting NMR-STAR file if proper key tag, such as 'ID', was missing in a loop. I am using v2.6.5.1 and v3. The problem relates category definitions for spectral peak lists, '_Peak_general_char', '_Peak_char', and '_Assigned_peak_chem_shift'. Could you run read/write test with the attached file including these categories, or provide solution to turn-off clean-up feature while output?

Best regards, 

Masashi

**Comment by jonwedell** [comment]
Dear Masashi,

Thank you for bringing this to my attention.

In the newest versions of the 3.x branch, the `Entry.write_to_file()` (and `Entry.format()`) functions support these arguments:

* `show_comments`:  Set to True/False to show/hide the comments before certain saveframes
* `skip_empty_loops` Set to True/False to omit/print loops that have no tag values for any tag *at all*.
* `skip_empty_tags` Set to True/False to omit/print tags without values

Due to an oversight, the library had a default value of `True` for `skip_empty_tags` for `Entry.write_to_file()` which is what caused the behavior you experienced. I changed the default value to `False` in 3.0.6 (just released) to address this. At the same time, you can get the desired behavior by setting `skip_empty_tags=False` in earlier 3.0.x releases without upgrading.

On the other hand, I cannot reproduce the error in the newest 2.x release, and that branch does not support the `skip_empty_tags` argument at all - all tags should always be printed. Can you provide the output file, and code to generate the output file from this input file that is omitting the tags on version 2.6.5.1?

Best,
Jon

**Comment by yokochi47** [comment]
Dear Jon,

Thank you for your kind support.
Then, I found a bug in my application that did the unexpected data manipulation.
Sorry for bothering you with this. This tickect is to be closed.

BTW, I always use skip_empty_tags=False in case v3 for our requirement.

Best regards,

Masashi
