### ISSUE TITLE
Release 3?

### ISSUE THREAD

**Issue by dspoel** [uwbmrb/PyNMRSTAR#88]
The latest release shown on the main github page is 2.6.x, shouldn't it be 3.0.4?

On a related not, is the software included in any package manager such as conda or pip?

Thanks!

**Comment by jonwedell** [comment]
Hello David,

~You're right, it's time I switch the master branch over to the documentation for version 3. The version 2 release was still considered the "primary" release for a while, but now v3 is well tested it's time to fix that.~

It is [available via](https://pypi.org/project/pynmrstar/) the PyPI package index from which pip draws packages. In fact, this is the way I recommend you obtain the software.

Running `pip3 install pynmrstar` will get you the newest version 3 release.

Cheers,
Jon

**Comment by jonwedell** [comment]
Ah, I see I slightly misunderstood your question: it isn't that the documentation shown is for the wrong version (I had updated that before) - it's that the newest releases of the software haven't been published as "releases" to GitHub. You're correct about that - I recommend installing from PyPI using pip in a virtual environment rather than manually downloading the package from GitHub.

That being said, I can resume uploading the releases on here if you depend on obtaining the packages this way - just let me know. The newest release available on PyPI is 3.0.6. ([Release notes](https://github.com/uwbmrb/PyNMRSTAR/blob/v3/documentation/release_notes.md#306).) I will look into making the package available via anaconda as well.

(I should really finish my morning coffee before beginning to respond to issues! 😀)

**Comment by dspoel** [comment]
Thanks for early morning answers! This makes it clear, but just the fact that there is a link with a released outdated version may get some people to use that instead of the latest and greatest.

**Comment by jonwedell** [comment]
Indeed; I've created [a release](https://github.com/uwbmrb/PyNMRSTAR/releases/tag/3.0.6) for 3.0.6 on the GitHub. Thanks for bringing this to my attention!
